version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: franc
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./guests.sql:/docker-entrypoint-initdb.d/guests.sql
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://franc:password@db:5432/example
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
